/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTemplatesIndexRouteImport } from './routes/app/templates/index'
import { Route as AppConversationsIndexRouteImport } from './routes/app/conversations/index'
import { Route as AppContactsIndexRouteImport } from './routes/app/contacts/index'
import { Route as AppCampaignsIndexRouteImport } from './routes/app/campaigns/index'
import { Route as AppTemplatesCreateRouteImport } from './routes/app/templates/create'
import { Route as AppContactsContactIdRouteImport } from './routes/app/contacts/$contactId'
import { Route as AppCampaignsCreateRouteImport } from './routes/app/campaigns/create'
import { Route as AppCampaignsCampaignIdRouteImport } from './routes/app/campaigns/$campaignId'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'
import { Route as ApiWhatsappStatusRouteImport } from './routes/api/whatsapp/status'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsIndexRoute = AppConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesCreateRoute = AppTemplatesCreateRouteImport.update({
  id: '/templates/create',
  path: '/templates/create',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsContactIdRoute = AppContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsCreateRoute = AppCampaignsCreateRouteImport.update({
  id: '/campaigns/create',
  path: '/campaigns/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsCampaignIdRoute = AppCampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => AppRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappStatusRoute = ApiWhatsappStatusRouteImport.update({
  id: '/api/whatsapp/status',
  path: '/api/whatsapp/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/whatsapp/status': typeof ApiWhatsappStatusRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/app/campaigns/create': typeof AppCampaignsCreateRoute
  '/app/contacts/$contactId': typeof AppContactsContactIdRoute
  '/app/templates/create': typeof AppTemplatesCreateRoute
  '/app/campaigns': typeof AppCampaignsIndexRoute
  '/app/contacts': typeof AppContactsIndexRoute
  '/app/conversations': typeof AppConversationsIndexRoute
  '/app/templates': typeof AppTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/whatsapp/status': typeof ApiWhatsappStatusRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/app/campaigns/create': typeof AppCampaignsCreateRoute
  '/app/contacts/$contactId': typeof AppContactsContactIdRoute
  '/app/templates/create': typeof AppTemplatesCreateRoute
  '/app/campaigns': typeof AppCampaignsIndexRoute
  '/app/contacts': typeof AppContactsIndexRoute
  '/app/conversations': typeof AppConversationsIndexRoute
  '/app/templates': typeof AppTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/whatsapp/status': typeof ApiWhatsappStatusRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/app/campaigns/$campaignId': typeof AppCampaignsCampaignIdRoute
  '/app/campaigns/create': typeof AppCampaignsCreateRoute
  '/app/contacts/$contactId': typeof AppContactsContactIdRoute
  '/app/templates/create': typeof AppTemplatesCreateRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
  '/app/contacts/': typeof AppContactsIndexRoute
  '/app/conversations/': typeof AppConversationsIndexRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/app/'
    | '/api/auth/$'
    | '/api/whatsapp/status'
    | '/api/whatsapp/webhook'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/create'
    | '/app/contacts/$contactId'
    | '/app/templates/create'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/conversations'
    | '/app/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/app'
    | '/api/auth/$'
    | '/api/whatsapp/status'
    | '/api/whatsapp/webhook'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/create'
    | '/app/contacts/$contactId'
    | '/app/templates/create'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/conversations'
    | '/app/templates'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/app/'
    | '/api/auth/$'
    | '/api/whatsapp/status'
    | '/api/whatsapp/webhook'
    | '/app/campaigns/$campaignId'
    | '/app/campaigns/create'
    | '/app/contacts/$contactId'
    | '/app/templates/create'
    | '/app/campaigns/'
    | '/app/contacts/'
    | '/app/conversations/'
    | '/app/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWhatsappStatusRoute: typeof ApiWhatsappStatusRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates/': {
      id: '/app/templates/'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversations/': {
      id: '/app/conversations/'
      path: '/conversations'
      fullPath: '/app/conversations'
      preLoaderRoute: typeof AppConversationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts/': {
      id: '/app/contacts/'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns/': {
      id: '/app/campaigns/'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates/create': {
      id: '/app/templates/create'
      path: '/templates/create'
      fullPath: '/app/templates/create'
      preLoaderRoute: typeof AppTemplatesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts/$contactId': {
      id: '/app/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/app/contacts/$contactId'
      preLoaderRoute: typeof AppContactsContactIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns/create': {
      id: '/app/campaigns/create'
      path: '/campaigns/create'
      fullPath: '/app/campaigns/create'
      preLoaderRoute: typeof AppCampaignsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns/$campaignId': {
      id: '/app/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/app/campaigns/$campaignId'
      preLoaderRoute: typeof AppCampaignsCampaignIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/status': {
      id: '/api/whatsapp/status'
      path: '/api/whatsapp/status'
      fullPath: '/api/whatsapp/status'
      preLoaderRoute: typeof ApiWhatsappStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCampaignsCampaignIdRoute: typeof AppCampaignsCampaignIdRoute
  AppCampaignsCreateRoute: typeof AppCampaignsCreateRoute
  AppContactsContactIdRoute: typeof AppContactsContactIdRoute
  AppTemplatesCreateRoute: typeof AppTemplatesCreateRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppConversationsIndexRoute: typeof AppConversationsIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCampaignsCampaignIdRoute: AppCampaignsCampaignIdRoute,
  AppCampaignsCreateRoute: AppCampaignsCreateRoute,
  AppContactsContactIdRoute: AppContactsContactIdRoute,
  AppTemplatesCreateRoute: AppTemplatesCreateRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppConversationsIndexRoute: AppConversationsIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWhatsappStatusRoute: ApiWhatsappStatusRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
